
title: Firefly AR
email: hello@fireflyar.io
description: >- # this means to ignore newlines until "baseurl:"
  Firefly AR!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fireflyar.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: fireflyar
facebook_username: FireflyAR
instagram_username: fireflyargame

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
